name: 'AWS Lambda Packager'
description: 'GitHub action that will package a Node.js project for deployment to AWS Lambda'
inputs:
  root:
    description: 'Project root directory'
    required: true
    default: '.'
  src:
    description: 'Project source directory, relative to root'
    required: true
    default: 'src'
  name:
    description: 'The name of the packaged project file. Default to GITHUB_SHA environment variable.'
    required: true
    default: ''
outputs:
  path:
    description: 'The directory path to the resulting packaged project'
  name:
    description: 'The file name of the resulting packaged project'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: archive
  color: orange
